/*
  # Insert Initial Data

  1. Insert sample elements
  2. Insert sample safety data
  3. Insert sample reactions
*/

-- Insert sample elements
INSERT INTO elements (symbol, name, atomic_number, atomic_mass, category, color, electron_configuration, melting_point, boiling_point, density, uses, safety_info, discovered_by, discovery_year, group_number, period, block, oxidation_states, electronegativity, ionization_energy, atomic_radius, crystal_structure) VALUES
('H', 'Hydrogen', 1, 1.008, 'nonmetal', '#ffffff', '1s¹', -259.16, -252.87, 0.08988, ARRAY['fuel', 'ammonia production', 'hydrogenation', 'rocket fuel'], 'Highly flammable gas. Can form explosive mixtures with air.', 'Henry Cavendish', 1766, 1, 1, 's', ARRAY[-1, 1], 2.20, 1312, 25, 'hexagonal'),
('He', 'Helium', 2, 4.003, 'noble-gas', '#d9ffff', '1s²', -272.2, -268.93, 0.1786, ARRAY['balloons', 'cryogenics', 'breathing gas', 'leak detection'], 'Inert gas. Can cause asphyxiation in enclosed spaces.', 'Pierre Janssen', 1868, 18, 1, 's', ARRAY[0], NULL, 2372, 28, 'face-centered cubic'),
('Li', 'Lithium', 3, 6.94, 'alkali-metal', '#cc80ff', '[He] 2s¹', 180.5, 1342, 0.534, ARRAY['batteries', 'ceramics', 'lubricants', 'psychiatric medication'], 'Highly reactive with water. Can cause burns.', 'Johan August Arfwedson', 1817, 1, 2, 's', ARRAY[1], 0.98, 520, 145, 'body-centered cubic'),
('C', 'Carbon', 6, 12.011, 'nonmetal', '#909090', '[He] 2s² 2p²', 3550, 4027, 2.267, ARRAY['steel production', 'diamonds', 'graphite', 'organic compounds'], 'Generally safe in solid form. Carbon monoxide is toxic.', 'Ancient', -3750, 14, 2, 'p', ARRAY[-4, -3, -2, -1, 0, 1, 2, 3, 4], 2.55, 1086, 70, 'diamond cubic'),
('O', 'Oxygen', 8, 15.999, 'nonmetal', '#ff0d0d', '[He] 2s² 2p⁴', -218.79, -182.96, 1.429, ARRAY['respiration', 'combustion', 'steel production', 'water treatment'], 'Supports combustion. High concentrations can be toxic.', 'Carl Wilhelm Scheele', 1774, 16, 2, 'p', ARRAY[-2, -1, 0], 3.44, 1314, 60, 'cubic'),
('Na', 'Sodium', 11, 22.990, 'alkali-metal', '#ab5cf2', '[Ne] 3s¹', 97.72, 883, 0.971, ARRAY['salt production', 'soap making', 'street lights', 'coolant'], 'Highly reactive with water. Produces hydrogen gas and heat.', 'Humphry Davy', 1807, 1, 3, 's', ARRAY[1], 0.93, 496, 180, 'body-centered cubic'),
('Cl', 'Chlorine', 17, 35.45, 'halogen', '#1ff01f', '[Ne] 3s² 3p⁵', -101.5, -34.04, 3.214, ARRAY['disinfection', 'bleaching', 'PVC production', 'water treatment'], 'Toxic gas. Corrosive to respiratory system.', 'Carl Wilhelm Scheele', 1774, 17, 3, 'p', ARRAY[-1, 1, 3, 5, 7], 3.16, 1251, 100, 'orthorhombic');

-- Insert sample safety data
INSERT INTO safety_data (element_symbol, hazard_level, hazard_types, precautions, first_aid, storage, disposal, incompatible_with, emergency_procedures) VALUES
('H', 'high', ARRAY['flammable', 'explosive'], ARRAY['Store in well-ventilated area', 'Keep away from ignition sources', 'Use explosion-proof equipment', 'Ground all equipment'], '{"inhalation": "Move to fresh air immediately. If breathing is difficult, give oxygen.", "skinContact": "Generally not applicable for gas, but if liquid contact occurs, treat for frostbite.", "eyeContact": "Flush with water for 15 minutes if liquid contact occurs."}', 'Store in cool, dry, well-ventilated area away from incompatible materials.', 'Allow gas to escape slowly in well-ventilated area or burn off safely.', ARRAY['oxidizers', 'halogens', 'nitrous oxide'], ARRAY['Evacuate area if large leak occurs', 'Eliminate ignition sources', 'Use water spray to disperse vapors']),
('O', 'medium', ARRAY['oxidizer', 'supports combustion'], ARRAY['Keep away from combustible materials', 'Use only with compatible equipment', 'Ensure proper ventilation'], '{"inhalation": "Move to fresh air. High concentrations may cause oxygen toxicity.", "skinContact": "Generally safe, but liquid oxygen can cause frostbite.", "eyeContact": "Flush with water if liquid contact occurs."}', 'Store in cool, dry area away from combustible materials.', 'Allow gas to escape slowly in well-ventilated area.', ARRAY['flammable materials', 'organic compounds', 'oils'], ARRAY['Remove combustible materials from area', 'Increase ventilation', 'Monitor oxygen levels']),
('Na', 'extreme', ARRAY['highly reactive', 'corrosive', 'fire hazard'], ARRAY['Store under mineral oil', 'Never expose to water', 'Use dry inert atmosphere', 'Wear full protective equipment'], '{"skinContact": "Remove contaminated clothing. Flush with water for 15 minutes. Seek immediate medical attention.", "eyeContact": "Flush with water for 15 minutes. Seek immediate medical attention.", "ingestion": "Do not induce vomiting. Give water to drink. Seek immediate medical attention."}', 'Store under mineral oil in airtight containers in cool, dry place.', 'React with alcohol to form sodium alkoxide, then dispose as hazardous waste.', ARRAY['water', 'alcohols', 'acids', 'halogens'], ARRAY['Evacuate area', 'Use dry sand or special dry powder to extinguish fires', 'Never use water']),
('Cl', 'high', ARRAY['toxic gas', 'corrosive', 'oxidizer'], ARRAY['Use in fume hood', 'Wear respiratory protection', 'Ensure emergency shower nearby', 'Monitor gas levels'], '{"inhalation": "Move to fresh air immediately. If breathing is difficult, give oxygen. Seek medical attention.", "skinContact": "Remove contaminated clothing. Flush with water for 15 minutes.", "eyeContact": "Flush with water for 15 minutes. Seek immediate medical attention."}', 'Store in cool, dry, well-ventilated area away from incompatible materials.', 'Neutralize with sodium hydroxide solution before disposal.', ARRAY['ammonia', 'hydrogen', 'metals', 'organic compounds'], ARRAY['Evacuate area', 'Use water spray to absorb gas', 'Wear full protective equipment']);

-- Insert sample reactions
INSERT INTO reactions (name, equation, reactants, products, reaction_type, energy_change, temperature, pressure, safety_warnings, description, yield_percentage, is_public, tags) VALUES
('Water Formation', '2H₂ + O₂ → 2H₂O', ARRAY['H2', 'O2'], ARRAY['H2O'], 'synthesis', -571.6, 298, 1, ARRAY['Highly exothermic reaction', 'Risk of explosion with hydrogen gas', 'Use proper ventilation'], 'The synthesis of water from hydrogen and oxygen gases. This is a highly exothermic reaction that releases significant energy.', 99.5, true, ARRAY['synthesis', 'combustion', 'water', 'hydrogen', 'oxygen']),
('Methane Combustion', 'CH₄ + 2O₂ → CO₂ + 2H₂O', ARRAY['CH4', 'O2'], ARRAY['CO2', 'H2O'], 'combustion', -890.3, 298, 1, ARRAY['Highly flammable gas', 'Ensure adequate ventilation', 'Risk of carbon monoxide formation in incomplete combustion'], 'Complete combustion of methane in oxygen, producing carbon dioxide and water vapor.', 98.2, true, ARRAY['combustion', 'methane', 'natural gas', 'energy']),
('Sodium Chloride Formation', '2Na + Cl₂ → 2NaCl', ARRAY['Na', 'Cl2'], ARRAY['NaCl'], 'synthesis', -822.0, 298, 1, ARRAY['Sodium is highly reactive with water', 'Chlorine gas is toxic', 'Violent reaction - use protective equipment'], 'Formation of table salt from sodium metal and chlorine gas.', 95.8, true, ARRAY['synthesis', 'ionic', 'salt', 'sodium', 'chlorine']);